set -q __fish_config_interactive; or return

alias ls='eza --icons --color=always --group-directories-first'
alias l='eza -lh --icons --color=always'
alias la='eza -a --icons --color=always'
alias ll='eza -lga --icons --color=always'
alias lsd='eza -d */ --icons --color=always'
alias lt='eza --tree --icons --color=always'
alias l1='eza -1 --icons --color=always'
alias cat='bat'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias grep='grep --color=auto'
alias vfzf='nvim (fzf -m --preview="bat --color=always {}")'
alias fzfpr='fzf --preview="bat --color=always {}"'
alias reload='exec fish'
alias q='exit'
alias c='clear'
alias ff='fastfetch'
alias oc='opencode'
alias zj='zellij'
